config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'articles#index', as: 'home'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
            length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>

  <% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <p class="mb-0"><%= msg %></p>
      </div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="card border-primary mb-3">
    <div class="card-header"><%= article.title %></div>
    <div class="card-body">
      <h4 class="card-title"><%= article.body %></h4>
      <!--      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
      <%= link_to "Read More", article_path(article), :class => 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>Post A New Article</h1>
<%= form_for :article, url: articles_path do |f| %>

  <% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <p class="mb-0"><%= msg %></p>
      </div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.body %></p>

<hr>

<%= link_to "Edit", edit_article_path(@article), :class => 'btn btn-primary' %>
<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="EN">
<head>
  <title>RailsTrial</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/lumen/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <span class="navbar-brand">
    <%= link_to "Article Posts", home_path, {:class => 'navbar-brand'} %>
  </span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item"> <%= link_to "New Entry", new_article_path, {:class => 'nav-link'} %> </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container py-3">
  <%= yield %>
</div>
</body>
</html>